# cleanup all the containers docker container prune
version: '3'
services:

  # clean: docker-compose run build-data mvn clean
  # build: docker-compose run build-data mvn clean install deploy
  build-data:
    image: maven:3.3-jdk-8
    container_name: lifehack-build-data
    working_dir: /home/app/src/   
    volumes: 
      - ./LifeHack.Data/:/home/app/src/
      - ./LifeHack.Data/target/:/home/app/target/
    build: 
      context: ./LifeHack.Data/

  # clean: docker-compose run build-api dotnet clean
  # build: docker-compose run build-api dotnet build
  # publish: docker-compose run build-api dotnet publish
  build-api:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    container_name: lifehack-build-api
    working_dir: /api/
    volumes: 
      - ./LifeHack/:/api/
    build: 
      context: ./LifeHack/

  # build: docker-compose run build-web npm run-script dist
  build-web:
    image: node:12.2.0
    container_name: lifehack-build-web
    working_dir: /web/
    volumes: 
      - ./LifeHackUI/:/web/
    build: 
      context: ./LifeHackUI

  neo4j:
    container_name: lifehack-neo4j
    image: neo4j:3.4
    ports:
      - "7474:7474"
      - "7687:7687"
    expose:
      - "7474"
      - "7687"
    volumes:
      - ./db/data:/data
    environment:
      - NEO4J_HEAP_MEMORY=2048
      - NEO4J_CACHE_MEMORY=1G
      - NEO4J_AUTH=neo4j/@abc123

  #Data Access Layer Endpoint
  data:
    container_name: lifehack-data
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - ./LifeHack.Data/target/webapps:/usr/local/tomcat/webapps
    links:
      - neo4j

  #Main C# .Net Core Api for the Application Services
  api:
    container_name: lifehack-api
    working_dir: /api/
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    command: dotnet /api/LifeHack.Api.dll
    restart: always
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8000:80"
    volumes: 
      - ./LifeHack/LifeHack.Api/bin/Debug/netcoreapp2.2/publish:/api/
    links: 
      - neo4j
      - data

  web:
    image: nginx:alpine
    container_name: lifehack-web
    ports: 
      - "4200:80"
    volumes: 
      - ./LifeHackUI/dist/LifeHackUI:/usr/share/nginx/html
    links: 
      - neo4j
      - data
      - api